project:
  type: website
  output-dir: docs

website:
  title: "431-labX"
  navbar:
    left:
      - text: "Lab X Instructions"
        href: index.qmd
    right:
      - text: "Contact Us"
        href: https://thomaselove.github.io/431-2023/contact.html
      - text: "Return to 431-labs page"
        href: https://github.com/THOMASELOVE/431-labs-2023
      - text: "Return to 431 main site"
        href: https://thomaselove.github.io/431-2023/

format:
  html:
    theme: cyborg
    date-format: iso
    toc: true
    link-external-icon: true
    link-external-newwindow: true

editor: source

