---
title: "431 Lab X"
subtitle: "Deadline: Tuesday 2023-12-12 at Noon"
author: "431 Staff"
date: last-modified
---

# What is this?

Lab X is an optional bonus lab, which consists of building a professional website.

This is, we hope, a worthwhile opportunity for you to build your own professional website. Not only will this give you some additional practice coding and using R and R-adjacent tools, it’s a low-cost and potentially high-yield method to establish your professional presence online. This is also an opportunity to learn how to use Quarto for more involved work than we'll do in 431 otherwise.

# How "optional" is this assignment?

Well, we earnestly hope **all of you** will do this assignment, and this is **especially** true for those of you in the PQHS or CRSP MS or PhD programs.

All students completing Lab X successfully (Dr. Love has to be able to open your website and read its contents) will receive a **substantial boost** to their course grade^[Dr. Love will define what a "substantial boost" means in December.]. 

Also, should you want Dr. Love to write a letter of recommendation for you in the future, he will be **much more willing** to do this if you have an active website.

# Instructions and Guidance

We want you to build a professional looking website that will be useful to you. The content is (mostly) up to you, but it’s worth considering using this opportunity to craft your online presence. 

## The Five Key Elements

Dr. Love will be happy if your site clearly includes at least the following five elements:

1. A front page including a photo of you or of something relevant to you.
2. Links to your social media presence, if any, and a way for people to get in touch with you via email.
3. An About Me or Welcome section on your front page, which briefly describes what you're doing now.
4. Some information on your Education, Experiences, and/or Projects
5. A way to download your CV

A blog is also an appealing way to connect your thoughts with the world, and including non-professional stuff is OK, too, of course.

# Using Quarto to Build the Site

Here are some resources that we think might be useful to you. If you find others that are helpful, please share them with us on [Campuswire](https://thomaselove.github.io/431-2023/campuswire.html).

- Quarto's general guide to [Creating a Website](https://quarto.org/docs/websites/) may also be helpful.
- Sam Csik has useful thoughts on [Creating your personal website using Quarto](https://ucsb-meds.github.io/creating-quarto-websites/)
- Marvin Schmitt provides a full tutorial and template at [Create Your Website with Quarto](https://www.marvinschmitt.com/blog/website-tutorial-quarto/). The template [shown here](https://marvinschmitt.github.io/quarto-website-template/), for example, gives you a great example of what I'm looking for.
- We found Drew Dimmery's [Quarto for an Academic Website](https://ddimmery.com/posts/quarto-website/) interesting and useful.
- [Chi Zhang's site](https://andreaczhang.github.io/qtwAcademic/articles/template_personal.html) provides a nice template for a personal site.
- The Quarto website shows you how to create a blog website within R Studio [in some detail here](https://quarto.org/docs/websites/website-blog.html).
- Beatriz Milz' [Creating a blog with Quarto in 10 Steps](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/)
- Albert Rapp's [The Ultimate Guide to Starting a Quarto Blog](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html)
- CrumpLab gives us [Blogging with Quarto: A 10 minute getting started tutorial](https://www.youtube.com/watch?v=YoKjBcuUP0s) (about 10 minutes)
- Isabella Velásquez at RStudio has a YouTube video called [Building a Blog with Quarto](https://www.youtube.com/watch?v=CVcvXfRyfE0) (just over an hour)
- Thomas Mock shows you how to [Create & Publish a Quarto Blog on Quarto Pub in 100 Seconds](https://www.youtube.com/watch?v=t8qtcDyCRFA)
- Joshua French has a playlist at YouTube of nine short videos that walk you through [Creating Websites with Quarto and Github](https://www.youtube.com/playlist?list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo)

## Can I use something other than R / Quarto to build my site?

Yes, but you'll receive less credit than a good Quarto site would receive. 

Good options to consider include [Owlstown](https://www.owlstown.com/), and [Wix](https://www.wix.com/), and each offers templates that would work nicely. 

Follow whichever approach is best for you and you feel most comfortable with. The key thing is to commit to making this a part of your life going forward, however you most effectively do that.

## What if I already have an active website?

If it includes the five elements listed above, great! You should definitely submit it to me as soon as possible.

## Should I spend a lot of money to have a fancy domain name?

No. There are many low-cost solutions if you want to register a domain and use it for this purpose. Google Domains can provide you with most available domains for something like $1 per month. I wouldn't go much above that, and a free name is even better.

## Do I need to wait until December to work on this?

Not at all. I would expect most of you to be able to follow the templates and guides above to do the work by early October. At the end of the term, you will have a lot of work to do, so getting to this early is definitely a good idea.

## Will the TAs help me troubleshoot my website?

If they can, sure, but only after anyone else looking for 431 help has had their problem settled. I do not guarantee that we can help fix your website problems.

# Some former students' websites built using R

These are mostly **not** built with Quarto, but instead with R Markdown, but give you some idea of what can be done...

- [Scarlett He](https://hsj957site.netlify.app/)
- [Catherine Heinzinger](https://drheinzinger.com/)
- [Zahin Islam](https://zahin-islam.netlify.app/)
- [Rock Lim](https://rocklim.netlify.app/)
- [Kristi Lin-Rahardja](https://kristilinr.netlify.app/)
- [Alex Olejko](https://alexolejko.netlify.app/)

# Submitting your Website

Submit a link to your website to Dr. Love in an email with the subject line **My Website** by the deadline specified in [the Course Calendar](https://thomaselove.github.io/431-2023/calendar.html). In the body of your email, briefly tell me how you created the site (Quarto, or something else.)

